development:
  adapter: postgresql
  encoding: unicode
  database: stadium_email_list_development
  pool: 5
test:
  adapter: postgresql
  encoding: unicode
  database: stadium_email_list_test
  pool: 5
production:
  adapter: postgresql
  encoding: unicode
  database: stadium_email_list_production
  pool: 5
